name: Test

on:
  push:
    branches: [ main, rewrite ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    name: Swift 5 on ${{ matrix.host.os }}
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: linux, os: ubuntu-latest, test-options: --enable-code-coverage, }
        ]
    runs-on: ${{ matrix.host.os }}
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run devcontainer task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: swift test

      


    
    