name: Test

on:
  push:
    branches: [ main, rewrite ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: Swift 5 on ${{ matrix.host.os }} using .devcontainer
    strategy: 
      fail-fast: false
      matrix: [
        { type: linux, os: ubuntu-latest, test-options: --enable-code-coverage, }
      ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3
      run: | 
        git config --global core.autocrlf input

    - name: Build and run devcontainer task
      if: matrix.host.uses-devcontainer
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          swift test -v -c debug ${{ matrix.host.test-options }}
          swift test -v -c release ${{ matrix.host.test-options }}

  build-native:
    name: Swift 5 on ${{ matrix.host.os }} natively
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: macos, os: macos-latest}
        ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3
      run: | 
        git config --global core.autocrlf input

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      run: swift --version
      
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0"
      run: llvm-config --version

    - name: Configure pkgconfig
      run: sudo ./Tools/make-pkgconfig.sh

    - name: Build (Debug)
      run: swift build -v -c debug

    - name: Test (Debug)
      run: swift test -v -c debug ${{ matrix.host.test-options }}

    - name: Build (Release)
      run: swift build -v -c release

    - name: Test (Release)
      run: swift test -c release -Xswiftc -enable-testing ${{ matrix.host.test-options }}


  
  