name: Test

on:
  push:
    branches: [ main, rewrite ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: "Devcontainer: ${{ matrix.host.os }}/${{ matrix.configuration }}"
    strategy: 
      fail-fast: false
      matrix: 
        host: [
          { type: linux, os: ubuntu-latest, test-options: --enable-code-coverage, }
        ]
        configuration: [ "debug", "release" ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - run: git config --global core.autocrlf input

    - name: Build and run devcontainer task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: swift test -v -c ${{ matrix.configuration }} ${{ matrix.host.test-options }}

  build-native:
    name: "Native: ${{ matrix.host.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: macos, os: macos-latest}
        ]
        configuration: [ "debug", "release" ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - run: git config --global core.autocrlf input

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1

    - run: swift --version
      
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0"

    - run: llvm-config --version

    - name: Configure pkgconfig
      run: sudo ./Tools/make-pkgconfig.sh /usr/local/lib/pkgconfig/llvm.pc

    - name: Build
      run: swift build -v -c ${{ matrix.configuration }}

    - name: Test 
      run: swift test -v -c ${{ matrix.configuration }} ${{ matrix.host.test-options }}
      
  build-native-windows:
    if: ${{ false }}  # disable for now
    name: "Native: ${{ matrix.host.os }}/release"
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: windows, os: windows-latest },
        ]
        swift: [
          { windows-branch: "swift-5.8-release", windows-tag: "5.8-RELEASE" }
        ]
    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Setup swift
      uses: compnerd/gha-setup-swift@main
      if: matrix.host.type == 'windows'
      with:
        branch: ${{ matrix.swift.windows-branch }}
        tag: ${{ matrix.swift.windows-tag }}

    - run: |
        git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Swift version
      run: swift --version

    - name: Set up LLVM 15.0.6
      run: |
        curl.exe -L -O -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"https://github.com/c3lang/win-llvm/releases/download/llvm_15_0_6/llvm-15.0.6-windows-x86-msvc17-libcmt.7z
        7z x llvm-15.0.6-windows-x86-msvc17-libcmt.7z -oC:\
        
    - name: Copy include in LLVM folder
      run: xcopy c:\llvm-15.0.6-windows-x86-msvc17-libcmt\include\*.* c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\14.34.31933\include /s /h

    - name: Copy lib in LLVM folder
      run: xcopy c:\llvm-15.0.6-windows-x86-msvc17-libcmt\lib\*.* c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\14.34.31933\lib\x64 /s /h

    - name: Add LLVM to Path
      run: Add-Content $env:GITHUB_PATH 'C:\llvm-15.0.6-windows-x86-msvc17-libcmt\bin'

    - run: llvm-config --version

    - name: Build (Release)
      id: first-build
      continue-on-error: true
      run: swift build -v -c release

    - name: Retry again on failure
      continue-on-error: false
      if: steps.first-build.outcome != 'success'
      run: swift build -v -c release

    - name: Test (Release)
      id: first-test
      continue-on-error: true
      run: swift test -c release -Xswiftc -enable-testing ${{matrix.host.test-options}}

    - name: Retry again on failure
      continue-on-error: false
      if: steps.first-test.outcome != 'success'
      run: swift test -c release -Xswiftc -enable-testing ${{matrix.host.test-options}}
